# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 123home CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  o123home-build-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: build api server file
      working-directory: ./
      run: npm run build --if-present

    - name: build api server file
      run: zip -r 123home.zip ./dist ./scripts ./src ./.eslintrc.js ./gitignore ./.prettierrc ./appspec.yml ./.production.env ./ecosystem.config.js ./package.json ./package-lock.json ./nest-cli.json ./README.md ./tsconfig.build.json ./tsconfig.json ./webpack-hmr.config.js

    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./123home.zip s3://123home-build/deploy/

    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name 123home-deploy
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name GROUP
        --s3-location bucket=123home-build,bundleType=zip,key=deploy/123home.zip
   
